### ISSUE TITLE
Existe algum release no mapa?

### ISSUE THREAD

**Issue by rafaeltcc** [RedeMocambos/plantio#28]
Prezados,

Me interessei por esse programa, tanto para utilizá-lo, quanto para contribuir com ele. Gostaria de saber como está o seu desenvolvivemento e se existe já um banco de dados público com as espécies.

Atenciosamente,

Rafael Rocha

**Comment by fernao** [comment]
Olá Rafael, tudo bem ?
O software plantio está sendo pensado há alguns anos, com algumas partes já desenvolvidas mas a maior parte não. O desenvolvimento estancou há algum tempo por falta de tempo e por não dispormos de um financiamento efetivo para bancar seu desenvolvimento.

Entretanto...! Há boas perspectivas para 2021! Está amadurecendo um projeto coletivo, que engloba um serviço (API) ligado a um banco de dados de espécies, alimentado por diversas pessoas. Considero como um software derivado da ideia do "plantio", ainda que não implemente o plano até aqui apresentado em sua completude.

Consideramos mais prudente desenvolver a princípio apenas uma parte (a parte central), de forma modular, em conjunto com outras pessoas - e destaco que será uma coletividade considerável.
Assim, ao disponibilizarmos um banco de dados com dados abertos, nos moldes da ciência cidadã, por meio de uma API, poderemos alçar vôos maiores no sentido de criar um ecossistema de softwares voltados para o plantio e acompanhamento de agroflorestas e sistemas de cultivo multidiversos.

Respondendo a questão: não existe release no mapa DESTE software específico, mas esperamos lançar em 2021 esse subproduto, de forma a oferecer uma ferramenta de apoio @s agrofloresteir@s e impulsionar essa forma de cultivo regeneradora e tão incrível.
