### ISSUE TITLE
Avaliar uso do mongo Db

### ISSUE THREAD

**Issue by fernao** [RedeMocambos/plantio#4]
https://www.ibm.com/developerworks/library/os-django-mongo/index.html

https://django-mongodb-engine.readthedocs.io/en/latest/

**Comment by fernao** [comment]
Possibilidade: utilizar banco convencional com possibilidade de usar campo texto para arquivo json.

**Comment by decko** [comment]
O Postgresql tem um campo especifico JSON, e uma versão "binária" chamado JSONB, q tem indices e dá pra fazer buscas com queries complexas.
